services:
  - type: web
    name: cra-app
    env: python
    buildCommand: ""
    startCommand: gunicorn cra.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: cra.settings
      - key: PYTHON_VERSION
        value: 3.11
