# Generated by Django 5.1.7 on 2025-04-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VCRA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='address',
            field=models.TextField(default='No Address Provided'),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='id_proof_number',
            field=models.CharField(default='Not Provided', max_length=50),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='id_proof_type',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='state',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
