# Generated by Django 5.1.7 on 2025-06-03 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VCRA', '0007_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='CivicUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('password', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('id_proof', models.CharField(max_length=50)),
                ('id_number', models.CharField(max_length=50)),
            ],
        ),
    ]
