# Generated by Django 5.1.7 on 2025-06-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VCRA', '0011_remove_complaint_complaint_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-06-05 00:00:00'),
            preserve_default=False,
        ),
    ]
