# Generated by Django 5.1.7 on 2025-06-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VCRA', '0012_complaint_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complaint_type',
            field=models.CharField(choices=[('Noise', 'Noise'), ('Pollution', 'Pollution'), ('Road damage', 'Road damage'), ('Other', 'Other')], default='No description', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='location',
            field=models.CharField(default='no description', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to='complaints/'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
