# Generated by Django 5.1.7 on 2025-06-12 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VCRA', '0014_alter_complaint_description_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
